### ISSUE TITLE
Why is the Product created in the Category entity class ? (in core) 

### ISSUE THREAD

**Issue by punkouter2018** [aspnetrun/run-aspnetcore#1]
Seems strange that a category is creating reports?

**Comment by mehmetozkaya** [comment]
Yes you are right, it is not meaningful, I was added this function due to give an example of loading responsibility into Entity classes, in this base repository there was no other place to add this functionality. Anyway I removed this function now, you can get latest version.
Also when I implemented real-world of this base repo in here I already removed that function -> [you can check AspnetCoreRealWorld - Category.cs](https://github.com/aspnetrun/run-aspnetcore-realworld/blob/master/src/AspnetRun.Core/Entities/Category.cs)
In real-world example this logic implemented at [Cart Entity](https://github.com/aspnetrun/run-aspnetcore-realworld/blob/master/src/AspnetRun.Core/Entities/Cart.cs) which basically added new items into shopping-cart use case.

**Comment by punkouter2018** [comment]
Ok. This has been very helpful for me to study and hope you don't mind more questions as I use this as a starting point.
