### ISSUE TITLE
Certificate on https://www.aspnetrun.com/

### ISSUE THREAD

**Issue by fowl2** [aspnetrun/run-aspnetcore#5]
This is probably the wrong place for this issue, but anyway- https://www.aspnetrun.com/ shows these error messages:

Firefox:

> The certificate is only valid for the following names: *.azurewebsites.net, *.scm.azurewebsites.net, *.azure-mobile.net, *.scm.azure-mobile.net, *.sso.azurewebsites.net
 > Error code: SSL_ERROR_BAD_CERT_DOMAIN

Chrome:

> This server could not prove that it is www.aspnetrun.com; its security certificate is from *.azurewebsites.net. This may be caused by a misconfiguration or an attacker intercepting your connection.

Hope this helps. =)

**Comment by mehmetozkaya** [comment]
The problem caused due to lack of certification of aspnetrun.com. Chrome dont allow to redirect http websites directly. For this domain I am using azure basic hosting option and unfortunately it is not included certification support. I will move this web site the another hosting to solve this certification problem soon.
But for now, you can pass this messages by clicking "Advance" and after that click the "Proceed aspnetrun.com". It will pass for upcoming requests.

**Comment by mehmetozkaya** [comment]
I updated the links of website with direct url of azure. So now its at least certificated url.
Please follow below url;
https://aspnetrun.azurewebsites.net/Discover

My current plan not supported so I dont want to change hosting now.
